### ISSUE TITLE
Example ... or what is the result

### ISSUE THREAD

**Issue by mitar** [Mitranim/prax#5]
So I read through the README, but I still do not get how it works. So how does the server side renders and how does then the client side know how to pick it from there and make elements dynamic and update with new data when necessary?

**Comment by mitranim** [comment]
Your view code consists of "markup" code and "behavior" code. To make hybrid SSR/SPA efficient, you have to separate them:

```js
import {E} from 'prax'

function Carousel() {
  return E(`a-caro`, {},
    E(`caro-item`, {}, `...`),
    E(`caro-item`, {}, `...`),
    E(`caro-item`, {}, `...`),
  )
}

class Caro extends HTMLElement {
  // Activate timers, buttons, etc.
  // This doesn't render children; they already exist.
  connectedCallback() {/* various callbacks, etc. */}
}
customElements.define(`a-caro`, Caro)
```

Both on the server and on the client, the _markup_ function `Carousel` prepares the DOM for the _behavior_ `Caro`. On first page load _and_ on each subsequent pushstate transition, this allows `Caro` to activate in-place, efficiently. On first page load, only behavior code should be loaded, not markup code.

Sometimes your custom element is partially prerendered, but occasionally needs to re-render the markup. Then it uses an async import to load markup code. I recommend minimizing the use of this pattern. It has the same problems as React: you'll need to refetch data or encode props into HTML as JSON.

```js
class SomeElem extends HTMLElement {
  async update() {
    const {SomeMarkup} = await import(`./view.mjs`)
    x.reset(this, {}, SomeMarkup())
  }
}
```

For client-only view code, everything is easier:

```js
class SomeElem extends HTMLElement {
  connectedCallback() {
    x.reset(this, {}, 
      E(`span`, {}, `child stuff`)
    )
  }
}
```

**Comment by mitar** [comment]
Thanks for the explanation!
